//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteSchool.Dtos
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    public partial class LogDto:BaseDto<int>
    {
        [DataMember]
        public override int Id { get; set; }

        [DataMember]
        public System.DateTime Date { get; set; }

        [DataMember]
        public string Level { get; set; }

        [DataMember]
        public string Message { get; set; }

        [DataMember]
        public string Exception { get; set; }

        [DataMember]
        public System.Guid Ticket { get; set; }
    }
}
